In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np
import math

In [1]:
# the rotation matrix used by reachy
R.from_matrix([
    [0, 0, -1],
    [0, 1, 0],
    [1, 0, 0],
]).as_euler('xyz', degrees=True)


C:\Users\62572\miniconda3\envs\spacy\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
  if __name__ == '__main__':


array([  0.        , -89.99999879,   0.        ])

In [59]:
# deg (degree) is the angle between the camera and the ground 
deg = 30
radian = math.radians(deg)
sin_angle = math.sin(radian)
cos_angle = math.cos(radian)
print(sin_angle)
print(cos_angle)

0.49999999999999994
0.8660254037844387


### when the robot and the camera are facing toward each other

In [60]:
# step 1: rotate along the x-axis by about +30 degrees
# this will first make the z axis (and the camera) be parallel to the ground,
R_x1 = np.array([
    [1, 0, 0],
    [0, cos_angle, -sin_angle],
    [0, sin_angle, cos_angle],
])
print(R_x1)
R.from_matrix(R_x1).as_euler('xyz', degrees=True)

[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]


array([30.,  0.,  0.])

In [40]:
# step 2: rotate along x-axis by +90 degrees (anti-clockwise)
R_x2 = np.array([
    [1, 0, 0],
    [0, 0, -1],
    [0, 1, 0],
])

R.from_matrix(R_x2).as_euler('xyz', degrees=True)

array([90.,  0.,  0.])

In [41]:
# step 3: rotate along z-axis by -90 degrees (clockwise)
R_z1 = np.array([
    [0, 1, 0],
    [-1, 0, 0],
    [0, 0, 1],
])

R.from_matrix(R_z1).as_euler('xyz', degrees=True)

array([  0.,   0., -90.])

In [61]:
M_opposite = R_x1.dot(R_x2).dot(R_z1)
print(M_opposite)

[[ 0.         1.         0.       ]
 [ 0.5        0.        -0.8660254]
 [-0.8660254  0.        -0.5      ]]


### when the robot and the camera is facing toward the same direction

In [18]:
# step 1: rotate along the x-axis by about +30 degrees

# step 2: rotate along the x-axis by +90 degrees

# step 3: rotate along z-axis by +90 degrees (anti-clockwise)
R_z2 = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1],
])

R.from_matrix(R_z2).as_euler('xyz', degrees=True)

array([ 0.,  0., 90.])

### when the robot is facing orthogonal to the camera (camera is on the right hand side of the robot)

In [ ]:
# step 1: rotate along the x-axis by about +30 degrees

# step 2: rotate along the x-axis by +90 degrees


### when the robot is facing orthogonal to the camera (camera is on the left hand side of the robot)

In [19]:
# step 1: rotate along the x-axis by about +30 degrees

# step 2: rotate along the x-axis by +90 degrees

# step 3: rotate along z-axis by 180 degrees (clockwise)
R_z3 = np.array([
    [-1, 0, 0],
    [0, -1, 0],
    [0, 0, 1],
])

R.from_matrix(R_z3).as_euler('xyz', degrees=True)


array([  0.,   0., 180.])

### Test the transformation matrix on a few points 

Here we assume that the camera is on the opposite side of the robot. So we use the matrix <i>M_opposite</i>. We also assume that the angle between the camera and the ground is 30 degrees. The results after the transformation are the coordinates of the object from reachy's perspective. 

In [62]:
# coord of the objects (from camera's perspective)
(x, y, z) = (0.01, 0.19, 0.55)

# translation vector (the distance between the origins of two coordinate systems based on reachy's view)
(d_x, d_y, d_z) = (0.8, -0.1, 0.15)

obj_vector = np.array([x, y, z])
obj_vector_r = obj_vector.dot(M_opposite)
obj_vector_t = np.array([obj_vector_r[0]+0.8, 
                         obj_vector_r[1]-0.1, 
                         obj_vector_r[2]+0.15])
print(obj_vector)
print(obj_vector_r)
print(obj_vector_t)

[0.01 0.19 0.55]
[-0.38131397  0.01       -0.43954483]
[ 0.41868603 -0.09       -0.28954483]
